import { authOptions } from "@/lib/auth";
import { GitHubClient } from "@/lib/github";
import { getServerSession } from "next-auth";
import { z } from "zod";

const createPRSchema = z.object({
  owner: z.string().min(1),
  repo: z.string().min(1),
  files: z.array(
    z.object({
      path: z.string().min(1),
      content: z.string(),
    })
  ),
  branchName: z.string().min(1).optional(),
  baseBranch: z.string().min(1).optional(),
});

export async function POST(request: Request) {
  const session = await getServerSession(authOptions);

  if (!session?.user?.accessToken) {
    return Response.json({ error: "Unauthorized" }, { status: 401 });
  }

  try {
    const body = await request.json();
    const { owner, repo, files, branchName, baseBranch } = createPRSchema.parse(body);

    const client = new GitHubClient(session.user.accessToken);
    const branch = branchName || `shipwright/deploy-${Date.now()}`;
    const base = baseBranch || (await client.getDefaultBranch(owner, repo));

    // Create a new branch
    const newBranch = await client.createBranch(owner, repo, branch, base);
    if (!newBranch) {
      return Response.json(
        { error: "Failed to create branch. Check that the base branch exists." },
        { status: 500 }
      );
    }

    // Commit each file to the new branch
    for (const file of files) {
      const result = await client.createOrUpdateFile(
        owner,
        repo,
        file.path,
        file.content,
        branch,
        `chore: add ${file.path} via Shipwright`
      );
      if (!result) {
        return Response.json({ error: `Failed to commit file: ${file.path}` }, { status: 500 });
      }
    }

    // Create the pull request
    const prTitle = "🚢 Shipwright: Add deployment configuration";
    const prBody = [
      "## Shipwright Deployment Configuration",
      "",
      "This PR was automatically generated by [Shipwright](https://github.com/VpkDevs/Shipwright) to prepare this repository for deployment.",
      "",
      "### Files Added",
      ...files.map((f) => `- \`${f.path}\``),
      "",
      "### Next Steps",
      "1. Review the generated files",
      "2. Fill in any missing environment variables in `.env.example`",
      "3. Merge this PR when ready",
      "4. Deploy to Vercel or your preferred hosting platform",
    ].join("\n");

    const pr = await client.createPullRequest(owner, repo, prTitle, prBody, branch, base);
    if (!pr) {
      return Response.json({ error: "Failed to create pull request" }, { status: 500 });
    }

    return Response.json({
      url: pr.html_url,
      number: pr.number,
      title: pr.title,
    });
  } catch (error) {
    if (error instanceof z.ZodError) {
      return Response.json({ error: "Invalid request parameters" }, { status: 400 });
    }

    console.error("Failed to create PR:", error);
    return Response.json({ error: "Failed to create pull request" }, { status: 500 });
  }
}
