import { authOptions } from "@/lib/auth";
import { getDb } from "@/lib/db";
import { pull_requests } from "@/lib/db/schema";
import { GithubApiError, RateLimitError, ValidationError } from "@/lib/errors";
import { GitHubClient } from "@/lib/github";
import { checkRateLimit } from "@/lib/rate-limit";
import { withErrorHandler } from "@/lib/with-error-handler";
import { getServerSession } from "next-auth";
import { z } from "zod";

const createPRSchema = z.object({
  owner: z.string().min(1),
  repo: z.string().min(1),
  repoId: z.string().optional(),
  files: z.array(
    z.object({
      path: z.string().min(1),
      content: z.string(),
    })
  ),
  branchName: z.string().min(1).optional(),
  baseBranch: z.string().min(1).optional(),
});

export const POST = withErrorHandler(async (request: Request) => {
  const session = await getServerSession(authOptions);

  if (!session?.user?.email) {
    throw new ValidationError("auth", "Not authenticated");
  }

  if (!session.user.accessToken) {
    throw new ValidationError("auth", "Missing access token");
  }

  const rateLimitResult = await checkRateLimit(session.user.email, "/api/create-pr");
  if (!rateLimitResult.success) {
    throw new RateLimitError(rateLimitResult.retryAfter || 60);
  }

  const body = await request.json();
  const { owner, repo, repoId, files, branchName, baseBranch } = createPRSchema.parse(body);

  try {
    const client = new GitHubClient(session.user.accessToken);
    const branch = branchName || `shipwright/deploy-${Date.now()}`;
    const base = baseBranch || (await client.getDefaultBranch(owner, repo));

    // Create a new branch
    const newBranch = await client.createBranch(owner, repo, branch, base);
    if (!newBranch) {
      throw new GithubApiError("Failed to create branch. Check that the base branch exists.");
    }

    // Commit each file to the new branch
    for (const file of files) {
      const result = await client.createOrUpdateFile(
        owner,
        repo,
        file.path,
        file.content,
        branch,
        `chore: add ${file.path} via Shipwright`
      );
      if (!result) {
        throw new GithubApiError(`Failed to commit file: ${file.path}`);
      }
    }

    // Create the pull request
    const prTitle = "Shipwright: Add deployment readiness plan";
    const prBody = [
      "## Shipwright Deployment Configuration",
      "",
      "This PR was automatically generated by [Shipwright](https://github.com/VpkDevs/Shipwright) to prepare this repository for deployment.",
      "",
      "### Files Added",
      ...files.map((f) => `- \`${f.path}\``),
      "",
      "### What to Review",
      "- Start with `SHIPWRIGHT_DEPLOYMENT_PLAN.md` if present",
      "- Confirm install, build, and start commands match this repository",
      "- Add real environment values in your hosting platform, not in this PR",
      "",
      "### Next Steps",
      "1. Review the generated files",
      "2. Fill in any missing environment variables in `.env.example`",
      "3. Merge this PR when ready",
      "4. Deploy to Vercel or your preferred hosting platform",
    ].join("\n");

    const pr = await client.createPullRequest(owner, repo, prTitle, prBody, branch, base);
    if (!pr) {
      throw new GithubApiError("Failed to create pull request");
    }

    // Log PR to DB
    const db = getDb();
    if (repoId) {
      try {
        await db.insert(pull_requests).values({
          repo_id: repoId as any,
          pr_number: pr.number,
          pr_url: pr.html_url,
          branch_name: branch,
          status: "open",
          generated_files: files.map((f) => f.path),
        });
      } catch (_e) {
        // Silently fail DB insert
      }
    }

    return new Response(
      JSON.stringify({
        url: pr.html_url,
        number: pr.number,
        title: pr.title,
      }),
      {
        status: 201,
        headers: { "Content-Type": "application/json" },
      }
    );
  } catch (error) {
    if (error instanceof z.ZodError) {
      throw new ValidationError("request", "Invalid request parameters");
    }
    throw error;
  }
});
