import type { DeploymentIssue, RepoAnalysis } from "@/types";

export function generateDeploymentPlan(
  owner: string,
  repo: string,
  analysis: RepoAnalysis,
  description?: string
): string {
  const issueRows = formatIssueRows(analysis.deploymentIssues);
  const envVars = analysis.envVarsDetected.length
    ? analysis.envVarsDetected.map((envVar) => `- \`${envVar}\``).join("\n")
    : "- No environment variable references detected.";
  const actions = analysis.recommendedActions.length
    ? analysis.recommendedActions.map((action) => `- [ ] ${action}`).join("\n")
    : "- [ ] Run the build command in CI before merging deployment changes.";
  const verificationCommands = [
    `${analysis.packageManager} install`,
    analysis.buildScript
      ? getRunCommand(analysis.packageManager, "build")
      : "# Add a build script before testing local verification",
    analysis.startScript
      ? getRunCommand(analysis.packageManager, "start")
      : "# Add a start script before testing production startup",
  ];

  return [
    `# Shipwright Deployment Plan for ${owner}/${repo}`,
    "",
    description ? `> ${description}` : "> Generated deployment readiness report.",
    "",
    "## Readiness",
    "",
    analysis.readinessSummary,
    "",
    `- Framework: ${analysis.framework}`,
    `- Package manager: ${analysis.packageManager}`,
    `- Lockfile: ${analysis.lockfile || "not detected"}`,
    `- Backend type: ${analysis.backendType}`,
    `- Dockerfile: ${analysis.hasDocker ? "present" : "not detected"}`,
    `- README: ${analysis.hasReadme ? "present" : "missing"}`,
    `- Environment example: ${analysis.hasEnvExample ? "present" : "missing"}`,
    `- Deployment risk score: ${analysis.deploymentRiskScore}/100`,
    "",
    "## Deployment Issues",
    "",
    "| Severity | Issue | Fix |",
    "| --- | --- | --- |",
    issueRows,
    "",
    "## Environment Variables",
    "",
    envVars,
    "",
    "## Recommended Actions",
    "",
    actions,
    "",
    "## Suggested Local Verification",
    "",
    "```bash",
    ...verificationCommands,
    "```",
    "",
    "## Hosting Notes",
    "",
    getHostingNotes(analysis),
    "",
    "---",
    "",
    "Generated by Shipwright.",
    "",
  ].join("\n");
}

function formatIssueRows(issues: DeploymentIssue[]): string {
  if (issues.length === 0) {
    return "| info | No deployment issues detected | Keep CI and preview deployments enabled. |";
  }

  return issues
    .map((issue) => {
      const issueText = issue.file ? `${issue.title} (\`${issue.file}\`)` : issue.title;
      return `| ${issue.severity} | ${escapeTableCell(issueText)} | ${escapeTableCell(issue.fix)} |`;
    })
    .join("\n");
}

function getRunCommand(packageManager: string, script: string): string {
  if (packageManager === "npm") return `npm run ${script}`;
  if (packageManager === "yarn") return `yarn ${script}`;
  if (packageManager === "pnpm") return `pnpm ${script}`;
  if (packageManager === "bun") return `bun run ${script}`;
  return `${packageManager} run ${script}`;
}

function getHostingNotes(analysis: RepoAnalysis): string {
  if (analysis.framework === "Next.js") {
    return [
      "- Vercel should auto-detect Next.js, but keep `vercel.json` when custom commands are needed.",
      "- Verify auth callback URLs and public environment variables in the preview deployment.",
    ].join("\n");
  }

  if (analysis.framework === "React" || analysis.framework === "Vue") {
    return [
      "- Confirm the build output directory before deploying.",
      "- Static hosts usually need a rewrite rule for client-side routes.",
    ].join("\n");
  }

  if (analysis.hasDocker) {
    return "- Docker is available, so container platforms can build from the Dockerfile if framework detection is incomplete.";
  }

  return "- Choose a hosting target, then align install, build, start, and environment variable settings with that platform.";
}

function escapeTableCell(value: string): string {
  return value.replace(/\|/g, "\\|").replace(/\n/g, " ");
}
