import { getInstallCommand, getRunScriptCommand } from "@/lib/package-manager";
import type { RepoAnalysis } from "@/types";

/**
 * Generates a GitHub Actions CI/CD workflow for Vercel deployment.
 * The workflow is individually tailored to the detected framework and package manager.
 *
 * Paid/AI-only artifact — not included in free template generation.
 */
export function generateGitHubActionsWorkflow(analysis: RepoAnalysis): string {
  const { framework, packageManager, buildScript, envVarsDetected } = analysis;

  const installCmd = getInstallCommand(packageManager);
  const buildCmd = buildScript || getRunScriptCommand(packageManager, "build");

  const isBun = packageManager === "bun";
  const isPnpm = packageManager === "pnpm";

  // Node.js setup step (always included)
  const nodeCache = !isBun && !isPnpm ? `\n          cache: "${packageManager}"` : "";
  const nodeSetup = `      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"${nodeCache}`;

  // pnpm setup (additional step before node if using pnpm)
  const pnpmSetup = isPnpm
    ? `\n\n      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false`
    : "";

  // Bun setup (replaces node for install/build if using bun)
  const bunSetup = isBun
    ? `\n\n      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest`
    : "";

  // Detected env vars to document in the workflow header (up to 6)
  const detectedVars = envVarsDetected
    .filter((v) => !["NODE_ENV", "PORT", "HOST"].includes(v))
    .slice(0, 6);

  const envVarComments =
    detectedVars.length > 0
      ? `#\n# Detected environment variables (add these to GitHub Secrets too):\n${detectedVars.map((v) => `#   ${v}`).join("\n")}\n`
      : "";

  // Build step env vars (inject detected secrets into build)
  const buildEnvSection =
    detectedVars.length > 0
      ? `\n        env:\n${detectedVars.map((v) => `          ${v}: \${{ secrets.${v} }}`).join("\n")}`
      : "";

  const frameworkNote = getFrameworkNote(framework);

  return `# ${frameworkNote}
# Generated by Shipwright — https://shipwright.dev
#
# Required GitHub Secrets (Settings → Secrets → Actions):
#   VERCEL_TOKEN       — https://vercel.com/account/tokens
#   VERCEL_ORG_ID      — from \`vercel link\` → .vercel/project.json
#   VERCEL_PROJECT_ID  — from \`vercel link\` → .vercel/project.json
${envVarComments}
name: CI/CD

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

env:
  VERCEL_ORG_ID: \${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: \${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  # ── Build & Validate ────────────────────────────────────────────────────
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

${nodeSetup}${pnpmSetup}${bunSetup}

      - name: Install dependencies
        run: ${installCmd}

      - name: Build
        run: ${buildCmd}${buildEnvSection}

  # ── Deploy to Vercel (main/master only) ─────────────────────────────────
  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel environment
        run: vercel pull --yes --environment=production --token=\${{ secrets.VERCEL_TOKEN }}

      - name: Build project artifacts
        run: vercel build --prod --token=\${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel (Production)
        id: deploy
        run: |
          url=\$(vercel deploy --prebuilt --prod --token=\${{ secrets.VERCEL_TOKEN }})
          echo "url=\$url" >> \$GITHUB_OUTPUT
          echo "Deployed to: \$url"

      - name: Comment deployment URL
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🚀 **Deployed to Vercel:** \${{ steps.deploy.outputs.url }}'
            })
`;
}

function getFrameworkNote(framework: string): string {
  switch (framework) {
    case "Next.js":
      return "GitHub Actions CI/CD — Next.js → Vercel";
    case "React":
      return "GitHub Actions CI/CD — React (Vite) → Vercel";
    case "Vue":
      return "GitHub Actions CI/CD — Vue → Vercel";
    case "Nuxt":
      return "GitHub Actions CI/CD — Nuxt → Vercel";
    case "Astro":
      return "GitHub Actions CI/CD — Astro → Vercel";
    case "Remix":
      return "GitHub Actions CI/CD — Remix → Vercel";
    case "Svelte":
      return "GitHub Actions CI/CD — SvelteKit → Vercel";
    case "Gatsby":
      return "GitHub Actions CI/CD — Gatsby → Vercel";
    case "Node.js":
      return "GitHub Actions CI/CD — Node.js → Vercel";
    default:
      return "GitHub Actions CI/CD → Vercel";
  }
}
